name: Testing Actions

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: [started]

env:
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initializing environment
      run: |
        df -h
        uname -a
