name: Building recovery

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-10.0
  DEVICE: RMX2185
  DT_LINK: https://github.com/HemanthJabalpuri/test
  DT_PATH: device/realme/RMX2185
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initializing environment
      run: |
        echo " ==== Initially ===="
        df -h
        docker rmi `docker images -q`
        git config --global user.name "HemanthJabalpuri"
        git config --global user.email "hemanthjabalpuri@gmail.com"
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+rx /usr/local/bin/repo

    - name: Sync recovery source and device tree
      run: |
        mkdir work
        cd work
        repo init -u $MANIFEST --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
        repo sync -j4
        git clone $DT_LINK --depth=1 --single-branch $DT_PATH

    - name: Building TWRP
      run: |
        cd work
        . build/envsetup.sh && lunch omni_${DEVICE}-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET

    - name: Uploading recovery image
      run: |
        cd work/out/target/product/$DEVICE
        sudo zip -r9 TWRP-${DEVICE}.zip recovery.img
        # Download transfer shell script and upload recovery to WeTransfer
        echo " ==== Finally ===="
        df -h
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet TWRP-${DEVICE}.zip
