name: Building recovery

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-10.0
  DEVICE: RMX2185
  DT_LINK: https://github.com/HemanthJabalpuri/test
  DT_PATH: device/realme/RMX2185
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initializing environment
      run: |
        echo " ==== Initially ===="
        df -h
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        docker rmi `docker images -q`
        echo " ==== Space after 1 ===="
        df -h
        sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
        git config --global user.name "HemanthJabalpuri"
        git config --global user.email "hemanthjabalpuri@gmail.com"
        echo " ==== Space after 2 ===="
        df -h
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get clean
        echo " ==== Space after 3 ===="
        df -h
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2
        echo " ==== Space after 4 ===="
        df -h
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+rx /usr/local/bin/repo

    - name: Sync recovery source and device tree
      run: |
        mkdir work
        cd work
        repo init -u $MANIFEST --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
        repo sync -j4
        echo " ==== Space after 5 ===="
        df -h
        git clone $DT_LINK --depth=1 --single-branch $DT_PATH

    - name: Building TWRP
      run: |
        cd work
        echo " ==== Space after 6 ===="
        df -h
        . build/envsetup.sh && lunch omni_${DEVICE}-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET
        echo " ==== Space after 7 ===="
        df -h

    - name: Uploading recovery image
      run: |
        cd work/out/target/product/$DEVICE
        sudo zip -r9 TWRP-${DEVICE}.zip recovery.img
        # Download transfer shell script and upload recovery to WeTransfer
        echo " ==== Space after 8 ===="
        df -h
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet TWRP-${DEVICE}.zip
